#==================================================
# CoreSales Backend
#==================================================
spring.application.name=service-product

#==================================================
# SERVER
#==================================================
server.port=8083

#==================================================
# OAUTH 2.0 RESOURCE SERVER
#==================================================
#spring.security.oauth2.resourceserver.jwt.issuer-uri=http://localhost:8081
spring.security.oauth2.resourceserver.jwt.issuer-uri=http://auth.coresales.local:8081

#==================================================
# DATABASE
#==================================================
#spring.datasource.url=jdbc:sqlserver://LAPTOP-U017LS9H;instanceName=SQLEXPRESS2022;databaseName=CoreSales;integratedSecurity=true;encrypt=true;trustServerCertificate=true
spring.datasource.url=jdbc:sqlserver://host.docker.internal:59890;instanceName=SQLEXPRESS2022;databaseName=CoreSales;integratedSecurity=true;encrypt=true;trustServerCertificate=true
#spring.datasource.username=
#spring.datasource.password=
spring.datasource.driver-class-name=com.microsoft.sqlserver.jdbc.SQLServerDriver

#==================================================
# JPA / HIBERNATE
#==================================================
#spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.database-platform=org.hibernate.dialect.SQLServerDialect
spring.jpa.hibernate.naming.physical-strategy=org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl

#==================================================
# JSON
#==================================================
#Indica que los atributos cuyo valor sea null no se incluiran en el JSON de respuesta:
spring.jackson.default-property-inclusion=non_null

#==================================================
# LOGGING
#==================================================
logging.level.root=INFO
logging.level.com.coresales.service.product=DEBUG

# Formato de consola
logging.pattern.console=%d{yyyy-MM-dd HH:mm:ss} %-5level [%thread] %logger{36} - %msg%n

# ==================================================
# ACTUATOR
# ==================================================
management.endpoints.web.exposure.include=health,info,metrics,prometheus
management.endpoint.health.show-details=always

# Datos informativos para mostrar en /actuator/info
info.app.name = service-product
info.app.version = 1.0.0
info.app.description = API de productos